{% set name = "vdms" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vdms-{{ version }}.tar.gz
  sha256: 8da315ee89c718a7773ddbd19986b716ccf4e7574c15e70a98d6433221fae8da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <4.0
    - pip
  run:
    - python <4.0
    - protobuf ==3.20.3

test:
  imports:
    - vdms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IntelLabs/vdms
  summary: VDMS Client Module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
